server:
  port: 8781
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order-service
# \u8BBE\u7F6Efeign\u8BF7\u6C42\u8D85\u65F6\u65F6\u95F4(\u4E00\u822C\u4E0D\u80FD\u8D85\u8FC7\u4E24\u79D2)
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 2000
